spring:
  cloud:
    config:
      server:
        git:
          uri: 'https://github.com/tibarix/movies-rating'
          #search-paths: '{application}'
          cloneOnStart: true

          
eureka:
  client:
    enabled: true
    service-url:
      default-zone: http://localhost:8761/eureka/
      
server:
  port: 1234
  