spring:
  cloud:
    config:
      server:
        git:
          uri: 'https://github.com/tibarix/movies-rating'
          #search-paths: '{application}'
          cloneOnStart: true

eureka:
  client:
    service-url:
      defaultZone: http://${ADRESSE:localhost}:4000/eureka
    enabled: true

server:
  port: 1234
  