version: '2'
services:
  eureka-server:
    image: movies-eureka-server
    expose:
      - "8761"
    ports:
      - "4000:8761"
  config-server:
    depends_on:
      - eureka-server
    image: movies-config-server
    expose:
      - "8081"
    ports:
      - "8000:1234"
    environment:
      server.port: 1234
      eureka.client.enabled: 'true'
      eureka.host: eureka-server
      eureka.instance.preferIpAddress: 'true'
  gateway:
    depends_on:
      - eureka-server
    image: movies-gateway
    expose:
      - "8060"
    ports:
      - "7000:8060"
    environment:
      server.port: 8060
      eureka.client.enabled: 'true'
      eureka.host: eureka-server
      eureka.instance.preferIpAddress: 'true'

