spring:
  application:
    name: movies-gateway

eureka:
  client:
    enabled: true
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}
server:
  port: 8060
zuul:
  routes:
    rating-service: /ratings/**
    movies-service: /movies/**

